services:
    Tapir\FormBundle\Form\Type\AjaxEntityType:
        class: 'Tapir\FormBundle\Form\Type\AjaxEntityType'
        tags:
            - { name: form.type }
        arguments: [ '@doctrine', '@router', '@?Tapir\FormBundle\Form\AjaxEntityManager' ]

    Tapir\FormBundle\Controller\AjaxEntityController:
        class: 'Tapir\FormBundle\Controller\AjaxEntityController'
        arguments: [ '@doctrine' ]

    Tapir\FormBundle\Form\Type\EntityIdType:
        class: 'Tapir\FormBundle\Form\Type\EntityIdType'
        arguments: [ '@doctrine' ]
        tags:
            - { name: form.type }

    Tapir\FormBundle\Form\Type\EntityHiddenType:
        class: 'Tapir\FormBundle\Form\Type\EntityHiddenType'
        arguments: [ '@doctrine' ]
        tags:
            - { name: form.type }
