# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ 'TapirBaseBundle' ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #cssembed:
        #    jar: %kernel.root_dir%/../vendor/packagist/cssembed-bin/bin/cssembed.jar
        #yui_js:
        #    jar: %kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar
        lessphp:
            #file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
            apply_to: "\.less$"
            formatter: "compressed"
            preserve_comments: false
        uglifyjs2:
            bin: %kernel.root_dir%/Resources/node_modules/uglify-js/bin/uglifyjs
        uglifycss:
            bin: %kernel.root_dir%/Resources/node_modules/uglifycss/uglifycss
    assets:
        #bootstrap_js:
        #    inputs:
        #        - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/transition.js'
        #        - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/alert.js'
        #        - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/modal.js'
        #        - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/dropdown.js'
        #        - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/scrollspy.js'
        #        - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js'
        #        #- '%kernel.root_dir%/../vendor/twbs/bootstrap/js/tooltip.js'
        #        - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/popover.js'
        #        - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/button.js'
        #        - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/collapse.js'
        #        #- '%kernel.root_dir%/../vendor/twbs/bootstrap/js/carousel.js'
        #        - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js'
        #    filters: [?uglifyjs2]
        #bootstrap_less:
        #    inputs:
        #        - '%kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less'
        #    filters: [lessphp,uglifycss]
        tapir_less:
            inputs:
                - '@TapirBaseBundle/Resources/less/tapir.less'
            filters: [lessphp,?uglifycss]
