parameters:
    tapir_usuarios_entidad: 'Yacare\BaseBundle\Entity\Persona'

twig:
    globals:
        tapir_nombreaplicacion: "Yacaré"
        tapir_cliente: %tapir.cliente%
        tapir_menu: 'YacareBaseBundle:Default:menu.html.twig'

assetic:
    assets:
        tapir_favicon: 'favicon.ico'
        tapir_css:
            inputs:
        tapir_js:
            inputs:
                        