imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: ../../vendor/knplabs/doctrine-behaviors/config/orm-services.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ['127.0.0.1', '10.0.0.1', '192.168.100.5'] # a list of proxy IPs you trust
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'YacareBaseBundle:Form:form_div_layout.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
      types:
        point: Knp\DoctrineBehaviors\DBAL\Types\PointType
      default_connection: default
      connections:
        default:
          driver:   "%database_driver%"
          host:     "%database_host%"
          port:     "%database_port%"
          dbname:   "%database_name%"
          user:     "%database_user%"
          password: "%database_password%"
          charset:  UTF8
          mapping_types:
            point: point
        v_catastro:
          driver:   "oci8"
          host:     "192.168.100.20"
          port:     "1521"
          dbname:   "rgr"
          user:     "yacare"
          password: "c4b4llo"
          charset:  UTF8

    orm:
      default_entity_manager: default
      auto_generate_proxy_classes: "%kernel.debug%"
      entity_managers:
        default:
          auto_mapping: true
          connection: default
#        v_catastro:
#          connection: v_catastro

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

jms_security_extra:
    # Enabling this setting will add an additional special attribute "ROLE_IDDQD".
    # Anybody with this attribute will effectively bypass all security checks.
    enable_iddqd_attribute: true
    # Enables expression language
    expressions: true

knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/bin/wkhtmltopdf
        options:    []
    image:
        enabled:    true
        binary:     /usr/bin/wkhtmltoimage
        options:    

stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    language: %locale%
    selector: ".tinymce"
    theme:
        simple:
            content_css: %web_root%/bundles/yacarebase/css/bootstrap-yacare.css
            plugins: "link paste spellchecker textcolor"
            toolbar1: "bold italic underline strikethrough | justifyleft justifycenter justifyright justifyfull | forecolor backcolor | removeformat | sub sup | undo redo spellchecker stfalcon"
            toolbar2: ""
            theme_modern_toolbar_location: "top"
            theme_modern_toolbar_align: "left"
            menubar: false
            statusbar: false
            paste_auto_cleanup_on_paste: true
            spellchecker_languages: "+Spanish=sp"
        medium:
            plugins: "table hr link paste spellchecker"
            toolbar1: "bold italic underline strikethrough | justifyleft justifycenter justifyright justifyfull | forecolor backcolor | hr removeformat | sub sup | spellchecker"
            toolbar1: "cut copy paste pastetext pasteword | bullist numlist | undo redo | link unlink | tablecontrols"
            theme_advanced_toolbar_location: "top"
            theme_advanced_toolbar_align: "left"
            menubar: false
            statusbar: false
            paste_auto_cleanup_on_paste: true
            image_advtab: true
            spellchecker_languages: "+Spanish=sp"
