imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
      default_connection: default
      connections:
        default:
          host:     "localhost"
          dbname:   "yacatest"
          user:     "yacatest"
          password: "123456"
          charset:  UTF8
          
security:
    firewalls:
        secured_area:
            security: false
