parameters:
    tapir_usuarios_entidad: 'Yacare\BaseBundle\Entity\Persona'

twig:
    globals:
        tapir_nombreaplicacion: "Yacaré"
        tapir_cliente: %tapir.cliente%
        tapir_menu: 'YacareBaseBundle:Default:menu.html.twig'

assetic:
    bundles:        [ 'YacareBaseBundle' ]
    assets:
        tapir_logoaplicacion:
            inputs:
                - '@YacareBaseBundle/Resources/public/img/muni_logo240.png'
        tapir_logoaplicacion16:
            inputs:
                - '@YacareBaseBundle/Resources/public/img/escudo64.png'
        tapir_logoaplicacion64:
            inputs:
                - '@YacareBaseBundle/Resources/public/img/escudo64.svg'
        tapir_favicon:
            inputs:
                - '@YacareBaseBundle/Resources/public/img/escudo64.png'
