yacare_recursos_humanos:
    resource: "@YacareRecursosHumanosBundle/Controller/"
    type:     annotation
    prefix:   /

yacare_inicio:
    resource: "@YacareInicioBundle/Controller/"
    type:     annotation
    prefix:   /inicio/

yacare_base:
    resource: "@YacareBaseBundle/Controller/"
    type:     annotation
    prefix:   /admin/

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
