yacare_base:
    resource: "@YacareBaseBundle/Controller/"
    type:     annotation
    prefix:   /base/

inicio:
    path:      /
    defaults:  { _controller: YacareBaseBundle:Default:inicio }
login_check:
    pattern:   /base/login_check
logout:
    pattern:   /base/logout
    
yacare_compras:
    resource: "@YacareComprasBundle/Controller/"
    type:     annotation
    prefix:   /compras/

yacare_tierras:
    resource: "@YacareTierrasBundle/Controller/"
    type:     annotation
    prefix:   /tierras/

yacare_organizacion:
    resource: "@YacareOrganizacionBundle/Controller/"
    type:     annotation
    prefix:   /organizacion/

yacare_catastro:
    resource: "@YacareCatastroBundle/Controller/"
    type:     annotation
    prefix:   /catastro/

yacare_inspeccion:
    resource: "@YacareInspeccionBundle/Controller/"
    type:     annotation
    prefix:   /inspeccion/

yacare_recursos_humanos:
    resource: "@YacareRecursosHumanosBundle/Controller/"
    type:     annotation
    prefix:   /rrhh/


