yacare_organizacion:
    resource: "@YacareOrganizacionBundle/Controller/"
    type:     annotation
    prefix:   /organizacion/

yacare_inicio:
    resource: "@YacareInicioBundle/Controller/"
    type:     annotation
    prefix:   /

yacare_base:
    resource: "@YacareBaseBundle/Controller/"
    type:     annotation
    prefix:   /base/

yacare_catastro:
    resource: "@YacareCatastroBundle/Controller/"
    type:     annotation
    prefix:   /catastro/

yacare_inspeccion:
    resource: "@YacareInspeccionBundle/Controller/"
    type:     annotation
    prefix:   /inspeccion/

yacare_recursos_humanos:
    resource: "@YacareRecursosHumanosBundle/Controller/"
    type:     annotation
    prefix:   /rrhh/


