yacare_sigemi:
    resource: "@YacareSigemiBundle/Controller/"
    type:     annotation
    prefix:   /sigemi/

yacare_bromatologia:
    resource: "@YacareBromatologiaBundle/Controller/"
    type:     annotation
    prefix:   /bromatologia/

yacare_zoonosis:
    resource: "@YacareZoonosisBundle/Controller/"
    type:     annotation
    prefix:   /zoonosis/

yacare_tramites:
    resource: "@YacareTramitesBundle/Controller/"
    type:     annotation
    prefix:   /tramites/

yacare_comercio:
    resource: "@YacareComercioBundle/Controller/"
    type:     annotation
    prefix:   /comercio/

yacare_base:
    resource: "@YacareBaseBundle/Controller/"
    type:     annotation
    prefix:   /base/

inicio:
    path:      /
    defaults:  { _controller: YacareBaseBundle:Default:inicio }
    
yacare_compras:
    resource: "@YacareComprasBundle/Controller/"
    type:     annotation
    prefix:   /compras/

yacare_organizacion:
    resource: "@YacareOrganizacionBundle/Controller/"
    type:     annotation
    prefix:   /organizacion/

yacare_catastro:
    resource: "@YacareCatastroBundle/Controller/"
    type:     annotation
    prefix:   /catastro/

yacare_inspeccion:
    resource: "@YacareInspeccionBundle/Controller/"
    type:     annotation
    prefix:   /inspeccion/

yacare_recursos_humanos:
    resource: "@YacareRecursosHumanosBundle/Controller/"
    type:     annotation
    prefix:   /rrhh/

_imagine:
    resource: .
    type:     imagine