app:
    resource: "routing_app.yml"
    
tapir_base:
    resource: "@TapirBaseBundle/Controller/"
    type:     annotation
    prefix:   /tapir/base/

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

login:
    path:      /login
    defaults:  { _controller: TapirBaseBundle:Default:login }

logout:
    path:      /logout

login_check:
    pattern:   /login_check