yacare_importar:
    resource: "@YacareImportarBundle/Controller/"
    type:     annotation
    prefix:   /

yacare_catastro:
    resource: "@YacareCatastroBundle/Controller/"
    type:     annotation
    prefix:   /catastro/

yacare_inspeccion:
    resource: "@YacareInspeccionBundle/Controller/"
    type:     annotation
    prefix:   /inspeccion/

yacare_base:
    resource: "@YacareBaseBundle/Controller/"
    type:     annotation
    prefix:   /admin/

yacare_inicio:
    resource: "@YacareInicioBundle/Controller/"
    type:     annotation
    prefix:   /inicio/

yacare_recursos_humanos:
    resource: "@YacareRecursosHumanosBundle/Controller/"
    type:     annotation
    prefix:   /rrhh/


