security:
    encoders:
        Yacare\BaseBundle\Entity\Persona:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: YacareBaseBundle:Persona, property: Username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern:    ^/base/login$
            anonymous:  ~

        secured_area:
            pattern:    ^/
            http_basic:
                realm: "Yacare"
            #form_login:
            #    login_path:  /base/login
            #    check_path:  /base/login_check
            #logout:
            #    path:   /base/logout
            #    target: /base/login
            #remember_me:
            #    key:      %secret%
            #    lifetime: 3600
            #    path:     /
            #    domain:   ~

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
