services:
    yacarebasebundle.twig.yacare_formatextension:
        class: Yacare\BaseBundle\Twig\FormatExtension
        tags:
        -  { name: twig.extension }
        
    adjuntos.type:
        class: Yacare\BaseBundle\Form\Type\AdjuntosType
        arguments: [ '@doctrine' ]
        tags:
            - { name: form.type, alias: adjuntos }
            
    yacare.base.base_listener:
        class: Yacare\BaseBundle\EventListener\BaseListener
        arguments: [ '@service_container' ]
        public:  false
        tags:
            - { name: doctrine.event_subscriber }
