@startuml

!include ../../Tapir/Base/UC_skinparam.skp

/'CASOS DE USO'/
(AF1 - Alta vehículo) as AF1
(AF2 - Suprimir vehículo) as AF2
(AF3 - Modificar vehículo) as AF3
(AF4 - Consultar vehículo) as AF4
(AF5 - Listar vehículo) as AF5
(AF6 - Registrar carga) as AF6

/'ACTORES'/
:Agente municipal: as actor1
:Administrador: as actor2

/'RELACIONES'/
actor1 -do- AF4 
actor1 -r- AF5 
actor1 -up- AF6 
AF1 ---- actor2
actor2 --up-- AF2
AF3 -- actor2
AF4 -r- actor2
actor2 -up- AF5 

AF2 <.. AF4 : extends
AF4 ..> AF3 : extends
AF2 <.. AF5 : extends
AF5 ..> AF3 : extends
AF6 <... AF4 : extends
AF6 <... AF5 : extends

@enduml
