parameters:
  tgen.twig_extension.class: Tapir\TemplateBundle\Twig\TgenExtension

services:
  tgen.twig.tgen_extension:
    class: '%tgen.twig_extension.class%'
    tags:
        - { name: twig.extension }
    
  # email type
  Tapir\TemplateBundle\Form\Type\EmailType:
      class: Tapir\TemplateBundle\Form\Type\EmailType
      tags:
          - { name: form.type }